In [ ]:
# For tips on running notebooks in Google Colab, see
# https://docs.pytorch.org/tutorials/beginner/colab
%matplotlib inline

Tensors
=======

Tensors are a specialized data structure that are very similar to arrays
and matrices. In PyTorch, we use tensors to encode the inputs and
outputs of a model, as well as the model's parameters.

Tensors are similar to NumPy's ndarrays, except that tensors can run on
GPUs or other specialized hardware to accelerate computing. If you're
familiar with ndarrays, you'll be right at home with the Tensor API. If
not, follow along in this quick API walkthrough.


In [64]:
import torch # GPU가 가속시킬수 있는 행렬연산 -> tensor / 그냥 numpy는 GPU 가속이 안되는 범부임
import numpy as np # numpy는 행렬연산하려고 만든거임 ㅇㅇ

data = [[1, 2], [3, 4]]
x_data = torch.tensor(data) # 이제 tensor에 태웠으니까 행렬 연산 빠름 ㅇㅇ

print(x_data) # tensor가 붙은 이유 -> 이 행렬은 GPU연산 Able
print(data) # 엄청난 차이가 있다!


np_array = np.array(data) # 리스트를 np array로 변경. 형변환임 ㅇㅇ
x_np = torch.from_numpy(np_array) # tensor로 가속이 되는 np array. 형변환임 ㅇㅇ

print(x_np)

x_ones = torch.ones_like(x_data) # retains the properties of x_data 1로 가득차버린 행렬(tensor, x_data는 tensor임)로 만듦
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data. 이것이 바로 weight의 초기값이 될 것임에 틀림없다
print(f"Random Tensor: \n {x_rand} \n")


shape = (2, 3,) #2행 3열의 행렬, 어떻게 내가 값을 다 침? 그러니까 형태를 지정해줘서 torch(행렬)를 바로 만드는거지
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Shape5_7 = (5, 7,) # 5행 7열로 만들기
rand_tensor_5_7 = torch.rand(Shape5_7)
print(f"Random Tensor: \n {rand_tensor_5_7} \n")


Shape3_5_7 = (3, 5, 7) # 3높이 5행 7열로 만들기. 마! 3차원 배열은! 맨 앞이 높이다 안카나?!
rand_tensor_3_5_7 = torch.rand(Shape3_5_7)
print(f"Random Tensor: \n {rand_tensor_3_5_7} \n")


tensor = torch.rand(3, 4) # 3행 4열짜리 랜덤 tensor 해줘

print(f"Shape of tensor: {tensor.shape}") #tensor의 행렬 크기
print(f"Datatype of tensor: {tensor.dtype}") #tensor의 데이터 타입. 디폴트는 float32
print(f"Device tensor is stored on: {tensor.device}") #tensor의 디바이스. 디폴트는 cpu / 너가 잘 뭔가 하면 gpu


# We move our tensor to the GPU if available
if torch.cuda.is_available(): # cuda가 깔려 있니?
  tensor = tensor.to('cuda') # cuda 깔려 있으면 GPU로 able
  print(f"Device tensor is stored on: {tensor.device}")

tensor = torch.ones(4, 4) # 4행 4열 행렬이고 1로 가득 차있음
tensor[:,2] = 0 # 슬라이싱 해버리면?! 모든 행의 2열을 0으로 바꿔 버리는 거임
print(tensor)


tensor = torch.zeros(3, 3) # 3행 3열 행렬이고 0으로 가득 차있음
tensor[1,:] = 1 # 슬라이싱 해버리면?! 모든 열의 1열을 1로 바꿔 버리는 거임
print(tensor)

print("\n 산을 표현한 수화")

empty_tensor = torch.zeros(3, 1)
fuck_tensor = torch.zeros(3, 3) # 3행 3열 행렬이고 0으로 가득 차있음
fuck_tensor[2,:] = 1 # 슬라이싱 해버리면?! 모든 열의 1열을 1로 바꿔 버리는 거임
fuck_tensor[:,1] = 1 # 슬라이싱 해버리면?! 모든 열의 1열을 1로 바꿔 버리는 거임
print(fuck_tensor)


t1 = torch.cat([fuck_tensor, empty_tensor, fuck_tensor], dim=1) # tensor 3개를 옆으로 쾅쾅쾅(효과음 아님) 합쳐버린거임
print(t1)


# This computes the element-wise product tensor랑 tensor를 곱하는것
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n") # 자기 자신이랑 곱하는건 mul 임 ㅇㅇ
# Alternative syntax: tensor랑 다른 tensor랑 곱하는거
print(f"tensor * fuck_tensor \n {tensor * fuck_tensor}")

dt1 = [[1, 2], [3, 4]]
dt2 = [[1, 2], [5, 6]]

tensor1 = torch.tensor(dt1)
tensor2 = torch.tensor(dt2)

print(f"tensor1 * tensor2 \n {tensor1 * tensor2}") # mul은 일반적인 행렬 곱하기가 아니라는 거임 ㅋㅋ
print(f"tensor2 * tensor1 \n {tensor2 * tensor1}") # 수학적인 행렬 쓰려면 matmul을 쓰셈

dt3 = [[1, 9], [0, 1]]
dt4 = [[5, 7], [4, 1]]

tensor3 = torch.tensor(dt3)
tensor4 = torch.tensor(dt4)

print(f"tensor3 * tensor4 \n {tensor3.matmul(tensor4)}")
print(f"tensor4 * tensor3 \n {tensor4.matmul(tensor3)}")

x1_data = torch.tensor(dt3)
x2_data = torch.tensor(dt4)

result = x1_data.sub(x2_data)
print(result)
print(x1_data - x2_data)

result = x1_data / x2_data
print(result)


# tensor를 다시 numppy로 바꾸는 거임
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

tensor([[1, 2],
        [3, 4]])
[[1, 2], [3, 4]]
tensor([[1, 2],
        [3, 4]])
Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.9644, 0.2700],
        [0.0039, 0.8845]]) 

Random Tensor: 
 tensor([[0.5412, 0.2783, 0.6374],
        [0.6605, 0.5606, 0.6104]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
Random Tensor: 
 tensor([[0.5983, 0.6230, 0.7897, 0.5525, 0.1372, 0.1721, 0.0603],
        [0.3792, 0.4377, 0.1194, 0.2790, 0.5049, 0.0846, 0.3513],
        [0.1008, 0.2726, 0.2030, 0.7157, 0.8206, 0.1736, 0.4990],
        [0.6820, 0.4883, 0.7552, 0.1387, 0.4545, 0.0048, 0.2869],
        [0.9021, 0.7841, 0.9861, 0.3978, 0.5878, 0.1991, 0.6399]]) 

Random Tensor: 
 tensor([[[0.5001, 0.8014, 0.6860, 0.5049, 0.6602, 0.9041, 0.4130],
         [0.2846, 0.0776, 0.1997, 0.1159, 0.5862, 0.2991, 0.8092],
         [0.8158, 0.4983, 0.6384, 0.1774, 0.8697, 0.1970, 0.7214],
         [0.8959

Tensor Initialization
=====================

Tensors can be initialized in various ways. Take a look at the following
examples:

**Directly from data**

Tensors can be created directly from data. The data type is
automatically inferred.


In [ ]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

**From a NumPy array**

Tensors can be created from NumPy arrays (and vice versa - see
`bridge-to-np-label`{.interpreted-text role="ref"}).


In [ ]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

**From another tensor:**

The new tensor retains the properties (shape, datatype) of the argument
tensor, unless explicitly overridden.


In [ ]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

**With random or constant values:**

`shape` is a tuple of tensor dimensions. In the functions below, it
determines the dimensionality of the output tensor.


In [ ]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

------------------------------------------------------------------------


Tensor Attributes
=================

Tensor attributes describe their shape, datatype, and the device on
which they are stored.


In [ ]:
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

------------------------------------------------------------------------


Tensor Operations
=================

Over 100 tensor operations, including transposing, indexing, slicing,
mathematical operations, linear algebra, random sampling, and more are
comprehensively described
[here](https://pytorch.org/docs/stable/torch.html).

Each of them can be run on the GPU (at typically higher speeds than on a
CPU). If you're using Colab, allocate a GPU by going to Edit \> Notebook
Settings.


In [ ]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
  print(f"Device tensor is stored on: {tensor.device}")

Try out some of the operations from the list. If you\'re familiar with
the NumPy API, you\'ll find the Tensor API a breeze to use.


**Standard numpy-like indexing and slicing:**


In [ ]:
tensor = torch.ones(4, 4)
tensor[:,1] = 0
print(tensor)

**Joining tensors** You can use `torch.cat` to concatenate a sequence of
tensors along a given dimension. See also
[torch.stack](https://pytorch.org/docs/stable/generated/torch.stack.html),
another tensor joining op that is subtly different from `torch.cat`.


In [ ]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

**Multiplying tensors**


In [ ]:
# This computes the element-wise product
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
# Alternative syntax:
print(f"tensor * tensor \n {tensor * tensor}")

This computes the matrix multiplication between two tensors


In [ ]:
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")
# Alternative syntax:
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

**In-place operations** Operations that have a `_` suffix are in-place.
For example: `x.copy_(y)`, `x.t_()`, will change `x`.


In [ ]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

<div style="background-color: #54c7ec; color: #fff; font-weight: 700; padding-left: 10px; padding-top: 5px; padding-bottom: 5px"><strong>NOTE:</strong></div>

<div style="background-color: #f3f4f7; padding-left: 10px; padding-top: 10px; padding-bottom: 10px; padding-right: 10px">

<p>In-place operations save some memory, but can be problematic when computing derivatives because of an immediate lossof history. Hence, their use is discouraged.</p>

</div>



------------------------------------------------------------------------


Bridge with NumPy {#bridge-to-np-label}
=================

Tensors on the CPU and NumPy arrays can share their underlying memory
locations, and changing one will change the other.


Tensor to NumPy array
=====================


In [ ]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

A change in the tensor reflects in the NumPy array.


In [ ]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

NumPy array to Tensor
=====================


In [ ]:
n = np.ones(5)
t = torch.from_numpy(n)

Changes in the NumPy array reflects in the tensor.


In [ ]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")